### PR TITLE
All test passed V8 8.9 PHP 7.4

### PR DESCRIPTION
**Pull request by waqasbelushi**

### CODE REVIEW

**Comment by stesie** [comment]
Thanks for the PR!

Really looks promising, unfortunately I haven't found time to give it a try myself so far.  Just triggered a compile cycle of a recent V8 version and then ran out of time ... I really hope for tomorrow

One question though already, why do you prefer to disable pointer compression? And have you tried if the `CPPFLAGS="-DV8_COMPRESS_POINTERS"` approach still works?

**Comment by waqasbelushi** [comment]
You'r Welcome @stesie 
No i do not try with pointer compression in build i disable v8_enable_pointer_compression=false then when i compile php add this ./configure --with-v8js=/opt/v8 LDFLAGS="-lstdc++" hope you understand my English is poor Thanks.

**Comment by waqasbelushi** [comment]
I'm also make simple vue 3 server side rendering script example 
<?php

$v8 = new V8Js();
$js = <<<JS
const { createSSRApp } = require('vue');
const { renderToString } = require('@vue/server-renderer');
const example= {
  template: `
    <div>
      Hello Worlds
    </div>`,
};
  const vueApp = createSSRApp(example);
  (async () => {
    const html = await renderToString(vueApp);
    print(html);
  })();
JS;
$v8->setModuleLoader(function ($module) {
	switch ($module) {
		case '@vue/compiler-core':
			return file_get_contents('node_modules/@vue/compiler-core/dist/compiler-core.cjs.prod.js');
			
		case '@vue/runtime-core':
			return file_get_contents('node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js');

		case '@vue/reactivity':
			return file_get_contents('node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js');

		case '@vue/compiler-ssr':
			return file_get_contents('node_modules/@vue/compiler-ssr/dist/compiler-ssr.cjs.js');


		case '@vue/shared':
			return file_get_contents('node_modules/@vue/shared/dist/shared.cjs.prod.js');

		case '@vue/compiler-dom':
			return file_get_contents('node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.prod.js');

		case '@vue/runtime-dom':
			return file_get_contents('node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.prod.js');

		case 'vue':
			return file_get_contents('node_modules/vue/dist/vue.cjs.prod.js');

		case 'vue-router':
			return file_get_contents('node_modules/vue-router/dist/vue-router.cjs.prod.js');
		
		case '@vue/server-renderer':
			return file_get_contents('node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js');
			
	}
});
try {
	$v8->executeString($js);
} catch (V8JsScriptException $e) {
	var_dump($e);
}

**Comment by stesie** [comment]
Hej @waqasbelushi, thanks once more for your contribution! :)

Finally I've found time to give it a try -- with pointer compression left enabled. Also I gave it a try with an older PHP version (7.3.21) and an older V8 version (8.0) ... which also worked just fine (passing the whole test suite)

Since old versions of V8 still work fine, I didn't want to modify the README to tell users to use V8 8.9 or higher --- but sure enough, using those old versions is not a good idea security wise. Also I didn't want to tell them to disable pointer compression...

Hence I've picked both of your commits with code changes to `php7` branch, leaving out the README modifications.

I hope you agree with that, otherwise please let me know or file another PR.

**Pull request closed without merging**
