### PR TITLE
support php8

### PR DESCRIPTION
**Pull request by amuluowin**
support php8

### CODE REVIEW

**Comment by stesie** [comment]
Hej Albert,

first of all, welcome as a v8js contributor :) and sorry that it took quite a while for me to respond.

... and thank you very much for coming up with this PR, great work :)

A few bits though:

1. currently some of the tests fail, at least with the versions I've tried it with (V8 8.9 and PHP 8.0.9):

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Test V8::executeString() : Script validator test [/app/tests/checkstring.phpt]
Test V8::executeString() : Exception clearing test [/app/tests/exception_clearing.phpt]
Test V8::executeString() : Exception propagation test 2 [/app/tests/exception_propagation_2.phpt]
Test V8::registerExtension() : Basic extension registering [/app/tests/extensions_basic.phpt]
Test V8::registerExtension() : Circular dependencies [/app/tests/extensions_circular_dependency.phpt]
Test V8::registerExtension() : Register extension with errors [/app/tests/extensions_error.phpt]
Test V8::executeString() : Fatal Error handler to ignore warnings [/app/tests/fatal_error_ignore_non_fatals.phpt]
Test V8Function() : Handle fatal errors gracefully [/app/tests/fatal_error_v8function.phpt]
Test V8::executeString() : Issue #250 (early free of array) [/app/tests/issue_250_001.phpt]
Test V8::executeString() : Object passing PHP > JS > PHP [/app/tests/object_passback.phpt]
Test V8::executeString() : var_dump [/app/tests/var_dump.phpt]
```

... nothing "critical" regarding the code, having a brief look, it's just wrong test expectations like

```
=== /app/tests/extensions_circular_dependency.diff ===
001+ Deprecated: Method V8Js::registerExtension() is deprecated in /app/tests/extensions_circular_dependency.php on line 3
001- Deprecated: Function V8Js::registerExtension() is deprecated in %s%eextensions_circular_dependency.php on line 3
[...]
```

Would you like to adapt the expectation so they are generic enough to match both PHP8 and prior versions? (and where not possible otherwise split tests like we did before)


2. in `v8js_v8object_class.cc` your auto-formatter seems to have gone a bit too far. In the rest of the code base opening curly braces (on if blocks, loops etc.) remain on the same line, this file is now reformatted that it goes to the next line

3. also in `v8js_v8object_class.cc` there are quite some copy & paste code portions surrounded by `#if PHP_VERSION_ID >= 80000` now and those (still) contain the `SINCE74(x, y)` `#ifdef` glue for PHP 7.4 compatibility.
Having compared some of the code, it looks mostly like type differences wrt. the `member` arg, and I wonder if it'd also be feasible to have some `SINCE80` macro instead of the duplication. What do you think?
Anyhow, I'm grateful for the patch, so if you think we can leave it like that.

regards

Stefan

**Comment by amuluowin** [comment]
I agree with you all.
I also think that the code is too much redundancy, but I don't know how to optimize it, can you optimize  the code?
Thanks.

**Comment by stesie** [comment]
@amuluowin I've modified `v8js_write_property` for demonstration purposes. What do you think? Would you like to go on from there?

**Comment by amuluowin** [comment]
Okay, I will continue to optimize other places

**Comment by amuluowin** [comment]
I optimize the redundancy code and fix some unit test yet.

**Comment by rbro** [comment]
I just wanted to check if we were closer to having a release that supports PHP 8.0.  Please let me know if there is any assistance needed.

Also, I tried the extension against PHP 8.1 and my initial tests seem to work successfully.  The only issue I've seen so far are the below deprecation warnings:

```
[05-Jan-2022 16:16:10 America/New_York] PHP Deprecated:  Return type of V8Generator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
[05-Jan-2022 16:16:10 America/New_York] PHP Deprecated:  Return type of V8Generator::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
[05-Jan-2022 16:16:10 America/New_York] PHP Deprecated:  Return type of V8Generator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
[05-Jan-2022 16:16:10 America/New_York] PHP Deprecated:  Return type of V8Generator::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
[05-Jan-2022 16:16:10 America/New_York] PHP Deprecated:  Return type of V8Generator::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
```

Thanks for your help.

**Comment by dieisraels** [comment]
Is there any chance that v8js will support PHP 8.x?

**Comment by websharik** [comment]
Server crashing with 502 code, on try set function value. Mb wrong V8 version ?

```PHP
$V8 = new V8Js();
$V8->someFunc = function () {}
```
PHP 8.0
V8 8.8.0

UPD: Yep, V8 since 8.8.278.17 resolved.

**Comment by websharik** [comment]
502 eror on try call v8 function... i was try many v8 versions, It did not help.

I try give XHR to JS to make XHR requests inside V8.

PHP XHR class part:
```PHP
//after request finished...
if (is_callable($this->onreadystatechange)) {
  call_user_func($this->onreadystatechange);
}
```
JS request part:
```JS
xhr.onreadystatechange = () => {
//...
}
```

So when PHP class call ```call_user_func($this->onreadystatechange);```, server return 502 error.

**Comment by redbullmarky** [comment]
@amuluowin @stesie i've tried picking this up a bit with limited knowledge...

Using ctx_lifetime test as a starting point, it always segfaults for me. In doing some crude debugging, it appears that `v8js_v8object_read_property` function inside of v8js_v8object_class.php is where the error pops up, and it'll happen regardless of the return value.

From the PHP side, this is called from the `var_dump($a->bar);` line (~line 29)

Any ideas?

**Comment by redbullmarky** [comment]
@amuluowin @stesie Made a little progress, at least as far as segfaults go...but I could really use a little help, even if just some pointers. As above, my knowledge of C++ is quite limited.

`ctx_lifetime.phpt` was segfaulting, but after changing `v8js_v8object_read_property` a little bit, it works. Basically, for the returns on lines ~143 and ~155 of `v8js_v8object_class.cc`, I changed them from `return retval;` to `return &EG(uninitialized_zval);`. My Google search came back with some protobuf code where a very similar thing is done there.

`object_passback.phpt` segfaults about 40% of the time.

Some of the other things were fixed because the tests needed amending for PHP8. So at this point, I'm left with two failing tests; one because of an output variation (not a break) and the other segfaults occasionally - when it doesn't, it passes the test.

But...then onto PHP8.1:
- Errors jumped from 2 to 16
- Made of of 8 that segfault all the time, 1 that segfaults sometimes (the same as PHP8.0), and the rest based on output diff rather than anything fatal etc.
- I had to run with error_reporting set to `E_ALL ^ E_DEPRECATION` else most of the tests failed. But this in itself caused one or two to fail because those were written with deprecation warnings coded into the test :-p

So....looking at the segfaults  a bit more with `gdb`, it seems they all land on `zend_fetch_debug_backtrace` and in particular this line (~1728 from php-src: `/Zend/zend_builtin_functions.c`):

```
		if (!fake_frame && func->common.function_name) {
```
and given that, it feels like it's one solution to fix the remaining failed tests. And whilst `fatal_error_v8function.phpt` test only fails on output, that difference according to its output is `unknown()` instead of `V8Function->V8Js::V8::Invoke()` in the trace which might be an indicator of the same problem.

So...any help would be hugely great. Not quite ready to give up on this one, yet! :)

**Comment by redbullmarky** [comment]
@amuluowin hey, i'm hoping to get a little more time later in the week to push my changes, as i've managed to get 100% of the tests passing for both PHP8.0 & 8.1 (and almost for 7.4 too within the same build).... when i do, it'd be great to have someone that actually seems to know this stuff better than myself to review/reject/criticize/tidy it up a bit...

glad to see someone else back here still working away on this thing!

**Comment by amuluowin** [comment]
> @amuluowin hey, i'm hoping to get a little more time later in the week to push my changes, as i've managed to get 100% of the tests passing for both PHP8.0 & 8.1 (and almost for 7.4 too within the same build).... when i do, it'd be great to have someone that actually seems to know this stuff better than myself to review/reject/criticize/tidy it up a bit...
> 
> glad to see someone else back here still working away on this thing!

Yes, the PHP7 & PHP8 are very different.
I think the PR make be merge to a new branch.

**Comment by redbullmarky** [comment]
@amuluowin i've committed my changes; i think a decent chunk of this is based on your work, plus some extras to fix a bunch of segfaults, as well as the test discrepancies between 7.x/8.0  and 8.1. it passes 100% of the tests for me on 8.0 and 8.1.

https://github.com/redbullmarky/v8js

**Comment by stesie** [comment]
> I think the PR make be merge to a new branch.

... also there's much condition stuff based on `PHP_VERSION_ID` going on. Plus many phpt tests are `TESTF` style just due to differing error messages between certain PHP versions. And then considering that PHP 7 only has security support for 7.4 (ending in a few months) ...

what do you think of ditching support for PHP < 8 alltogether? Still we could keep the `php7` branch, ... just provide some `php8` (or `main`?) and make that the new default branch.

**Comment by redbullmarky** [comment]
@stesie i think 7.4 is still common enough to at least support bug fixes / security issues, though apart from a few things, it’s quite stable. We push it very hard and in some very odd ways, and the issues raised in my other open issue are the only ones I personally encounter. 

Certainly a new branch is required.

**Comment by redbullmarky** [comment]
@amuluowin Latest commit to php7 branch is applicable to php8 also

**Comment by stesie** [comment]
Hej all :-)

... finally I've created a new `php8` branch (as requested here earlier), based on @amuluowin's great work 🎉 
Also I've changed the repo's default branch to that new branch.  This is if you clone the repo now, you'll get the `php8` stuff.

I've also changed the README file to tell that PHP8 is required and added a little pointer to the `php7` branch.

Since we've gone with a new branch instead of having one that supports both PHP7 & PHP8, I've ditched all the `SINCE74` and `SINCE80` macros plus must of the other PHP_VERSION_ID dependent preprocessor fluff.

So again, thanks @amuluowin and @redbullmarky for your work... and also for poking me to finally have a look :)

As this PR is targeting `php7` branch I'm technically closing the PR, ... but all the goodness went into the new and shiny `php8` branch.

**Comment by redbullmarky** [comment]
@stesie amazing! What should be done about the version number/tagged release? That one is a bit behind the times.

**Comment by stesie** [comment]
hmm, I wonder whether to publish version 2.2.0 with `php8` branch as is, ... or remove all the things marked deprecated (pending exceptions, v8 extensions & checkString method) and release 3.0.0

any opinions on that one?

**Comment by redbullmarky** [comment]
3.0.0 sounds most logical to me for PHP8, it’s a clear and obvious separation. 

And retag the 2.x one too as there have been some fixes since the last tag

**Comment by temuri416** [comment]
So excited by the prospect of PHP8 support!

**Pull request closed without merging**
