### PR TITLE
Php8 propagate exception magic methods

### PR DESCRIPTION
**Pull request by chrisbckr**
refs #437

### CODE REVIEW

**Comment by stesie** [comment]
LGTM

🚀 🔥  thanks again :-) 🔥 🚀

**Comment by redbullmarky** [comment]
@chrisbckr you’re on fire! Are you planning to clear out the Issues list entirely? 😂

**Comment by chrisbckr** [comment]
> @chrisbckr you’re on fire! Are you planning to clear out the Issues list entirely? 😂

This is a challenge? 🤣 

But really... I started studying what I could do with this module in 2018. I use V8Js a lot and this help me on ways that you can't imagine. 
This is the minimum that I can do, considering my limited knowledge in C++.
Some simple contributions, but a real challenge for me haha
💪🏻

**Comment by redbullmarky** [comment]
@chrisbckr Haha, it'd be a great challenge ;-)

I think we're in a similar boat. Here, we've used V8Js extensively for several years and really push the limits of what it can do, so it's normal to find the occasional issue or something you'd like it to be able to do.

@stesie has been great for as long as I've been using the project, but it's a lot to ask of one person to fix and improve everything! I'm trying to give bits and pieces back to the project where time and knowledge can afford, but it's great to see more people here doing the same too :) V8Js is awesome, and surprisingly unique - there are barely any PHP extensions that do the same.

Anyway, I'm checking in here most days at the moment so happy to help out where I can!
Mark.

**Comment by stesie** [comment]
Yes, go for it! 🎉 

I really appreciate that and what both of you keep contributing.  And it really makes me happy that there are still people actively using and improving it.  Times when I was actively using it are long gone (I left that company back in 2016) ... and there were phases I was struggling maintaining it.

So again a really big thanks to you.  Your contributions really motivate me to look after it.  I suppose that you noticed that my response times were plummeting recently 🙂

**Pull request merged**
