### PR TITLE
Reflect libv8 PPA changes

### PR DESCRIPTION
**Pull request by pinepain**

### CODE REVIEW

**Comment by pinepain** [comment]
I'm moving away from PHP world and all my PHP projects going to be abandoned too. Abandoning this PR too as I have no intent to continue working on it unless there would be strong request from community and commercial interest. No more updates or documentation will be made. If someone is interested, feels free to contact me using email specified in my GitHub profile.

**Comment by virgofx** [comment]
@pinepain does that mean PPA builds for libv8 will discontinue? I wouldn't mind moving the part that builds libv8 into v8js organization and then subsequently update v8js to automatically look in these paths. (Would make installation way easier) Would you be open in assisting/helping with this effort? Basically, here's what I'm thinking specifically:
* Add new libv8 repository in phpv8 org.
* Set it up to autobuild nightly/weekly (to your existing PPA, setup a new one or setup more agnostic open source/free version @ packagecloud) 
* UPdate V8JS to detect the default paths -- for PECL install of v8js.

I realize traditionally supporting semi-automatic builds for the existing PPA structure is somewhat tedious; however, could your last effort be made to setup a streamlined/automatic system that builds various versions across different platforms?

I think that would be incredibly useful as the build process is very long for libv8 and it would allow users to still easily use PHP with up-to-date V8 versions.

Thoughts?

**Comment by pinepain** [comment]
Hi @virgofx! Correct, PPA builds for anything related to my PHP projects and related dependencies won't be updated anymore. I'm more then welcomed to transfer [pinepain/php-v8](https://github.com/pinepain/php-v8/), [pinepain/php-v8-stubs](https://github.com/pinepain/php-v8-stubs), [pinepain/dockerfiles](https://github.com/pinepain/dockerfiles) and [pinepain/ppa-packaging](https://github.com/pinepain/ppa-packaging) and assist with the future of v8 in PHP pro-bono.

As to libv8 release process, it's covered by https://php-v8.readthedocs.io/en/latest/development/release-libv8.html (you want to look at other docs section), so it should lower the barrier to get started with building it to the separate PPA.

I have to add that at the end of my route with PHP I used to containers so I personally have no interest in building libv8 packages across different platforms. From what I know, there is [5918 issue](https://bugs.chromium.org/p/v8/issues/detail?id=5918) (Consider hosting pre-built binaries for each OS/arch somewhere official), however when I was looking into it last time, it did not fit my (php-v8) needs. Honestly, I have no time to spend on the internet asking to make things works different for few people and it was much simpler to build v8 by myself. V8 devs are great, don't get me wrong, I just see no practical use apart of me and few other nerds (that's one of the reasons why I move out from PHP as I just can't have nice things).

Long time ago there was an idea to use php-v8 as ground to rewrite v8js to make it more high-level, that's basically what I was trying to prepare to in [pinepain/js-sandbox](https://github.com/pinepain/js-sandbox), which I also don't mind to transfer is someone is interested to maintain (it has [pinepain/php-ref](https://github.com/pinepain/php-ref) as dependency, fyi). You may ask @stesie what's his plans on this.

P.S. I heard that there is new [dstogov/php-ffi](https://github.com/dstogov/php-ffi) extension that adds FFI to PHP, which potentially could make php<->v8 layer provided by php-v8 redundant, though, less likely it would be reliable, anyway, if someone is curious, just give it a try.

**Comment by virgofx** [comment]
I know I would be interested in either moving `ppa-packaging` or the 5918 issue pre-built binaries for each OS as this would be incredibly valuable. The dockerfiles repo is small, we could move it over straight (I don't see any maintenance really for this).

As for the php-v8 and stubs ... I haven't used the project and don't have enough insight. It's really up to @stesie if he wants to move those into the organization and un-archive them (or not?) I don't know if there are any other maintainers other then yourself ... I don't think stesie will have the time so it's really more of a long-term solution

**Comment by pinepain** [comment]
It's up to you, folks. Just ping/mail me  whenever you need my help and I'll try to find some time for that.

**Pull request closed without merging**
