### PR TITLE
Update appveyor.yml for issue 306

### PR DESCRIPTION
**Pull request by Jan-E**
Use these v8js builds: https://github.com/phpv8/v8js/issues/306#issuecomment-294258612

### CODE REVIEW

**Comment by Jan-E** [comment]
@stesie You do not have to merge this PR. But you will have to change the dependencies in the appveyor.yml to merge https://github.com/phpv8/v8js/pull/307 and fix https://github.com/phpv8/v8js/issues/306

**Comment by stesie** [comment]
Sure, yet haven't found the time to finally do it.

You might have seen that I already incorporated your changes in #307, just some debugging fluff in the `appveyor.yml` left to remove and then merge.

I've taken your ZIP files, thanks once more for creating those, and removed all the debug stuff to save on traffic

**Comment by Jan-E** [comment]
OK. I did not see the changes in https://github.com/phpv8/v8js/pull/307 yet.

**Comment by stesie** [comment]
I've merged your changes with #307 meanwhile, thanks for providing the pre-compiled V8 assets :-)

**Pull request closed without merging**
